Fixed a couple of typos
Predeactor/Predeactor-Cogs pull request #45
Opened 2021-07-01 03:02 UTC by Onii-Chan-Discord

2021-07-01 10:59 UTC, Predeactor requested changes
The following comments are what I do not appreciate in this PR.
I would like the revert of the "people" change most especially, it doesn't fit well at all.

2021-07-01 10:59 UTC, Predeactor commented on letters/commands/letterbox.py
> +                + "  able to recovere this letter afterwards.",
There is a double space here.

2021-07-01 10:59 UTC, Predeactor commented on letters/commands/letterbox.py
> +            await msg.edit(content="Cancelling deletion")
I don't like this edit, please revert it.

2021-07-01 10:59 UTC, Predeactor commented on letters/commands/writer.py
> +            ctx, "Do you know the IDs/names of the people I must contact?"
"people" is not a term I agree with, this make the sentence strange to read.

2021-07-01 10:59 UTC, Predeactor commented on letters/commands/writer.py
> +            "Please give me the name, mention, or ID of the people you want to send a letter "
This is even more weird.

2021-07-01 10:59 UTC, Predeactor commented on letters/commands/writer.py
> +            await ctx.send("I can't send a letter to more than 5 people, sorry!")
Same as before.

2021-07-01 10:59 UTC, Predeactor commented on letters/commands/writer.py
> +        msg = "I have found the following users, are they the correct users?\n" + "\n".join(
Is there a space between "user" and "s"? If so please fix that.

2021-07-01 15:57 UTC, Predeactor commented on letters/commands/writer.py
> +        msg = "I have found the following users, are they the correct users?\n" + "\n".join(
Was just my phone showing me weird things...

2021-07-13 21:59 UTC, Onii-Chan-Discord commented on letters/commands/writer.py
> +            "Please give me the name, mention, or ID of the people you want to send a letter "
So should i revert this change?

2021-07-13 22:00 UTC, Onii-Chan-Discord commented
Fixed all of the requested changes except 1.

2021-07-13 22:00 UTC, Predeactor commented on letters/commands/writer.py
> +            "Please give me the name, mention, or ID of the people you want to send a letter "
Yes please do.

2021-07-13 22:05 UTC, Onii-Chan-Discord commented
I believe all requested changes have been made

2021-07-13 22:07 UTC, Predeactor approved these changes

2021-07-13 22:07 UTC, merged

2021-07-13 22:07 UTC, Predeactor commented
Thank for the PR.